<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <p>
      <span style="color:grey">
        <i>&#60;A man and a child stand on a pathway in a dark expanse with little blob beings encased in chains&gt;</i>
      </span>
    </p>
    <p>Child: “What are these?”</p>
    <p>Man: “They are concepts that people have claimed as their own.”</p>
    <p>Child: “Why are they in chains?”</p>
    <p>
      Man: “They have been disconnected from their original source. They have become enslaved by the minds of people.”
    </p>
    <p>Child: “But they look unhappy!”</p>
    <p>
      Man: “Ideas are born free. They move fluidly through the level of causation. When people catch an idea, they keep
      them for their own. They claim them. Make them static. They are no longer connected to the purity of the higher
      archetypal levels. When this occurs, the idea can no longer pull from the beauty of the archetypal levels. They
      become frozen concepts in time.”
    </p>
    <p>Child: “What will happen to them?”</p>
    <p>
      Man: “If an idea is no longer connected to its source, it cannot grow, or evolve, or populate other ideas. When
      this happens, eventually the idea will be outgrown. And it will die.”
    </p>
    <p>Child: “That’s horrible!”</p>
    <p>
      Man: “It is. But worse still, are those ideas who refuse to die. Being disconnected from their original source,
      they need fuel from somewhere else. This fuel comes from the minds and emotions of people. When an idea becomes
      too charged from this source, then they cannot die. And so become stuck. Unchanging, yet completely convinced of
      the necessity of its existence.”
    </p>
    <p>Child: “But I thought it was good to have ideas?”</p>
    <p>
      Man: “It is! Ideas are there to be caught and played with and brought into existence. But one must never mistake
      an idea to be something that one owns. Ownership assumes origin. And an idea should never be disconnected from its
      source. How would you feel if you were disconnected from where you came from?”
    </p>
    <p>
      <span style="color:grey">
        <i>&#60;The Child is silent and looks at the images of the ideas being shown to him&gt;</i>
      </span>
    </p>
    <p>Child: “Have things always been this way?”</p>
    <p>Man: “No, things were not always this way. And they are also not now.”</p>
    <p>Child: “I don’t understand.”</p>
    <p>Man: “A story perhaps, with words and images as poor paint:”</p>
    <p>
      Man: “Long ago, as it was then, is now, and always. Knowledge and Life were together. Life was the fuel of
      Knowledge, and Knowledge the carrier of Life. Inseperable they were, for all things bathed and were created in
      their Light. Beauty was in everything, because form was never without breath and breath shone always with the
      Light of Life. All things were known, and all things had their place.”
    </p>
    <p>
      Man: “Knowledge and Life reveled in their creation, but a time came when they became restless because they
      realised there was one thing they did not know. That they could not create.”
    </p>
    <p>Child: “What was it?”</p>
    <p>Man: “They did not know what it was like to be without each other.”</p>
    <p>Child: “Oh.”</p>
    <p>
      Man: “And so, spending their last moment together, enjoying their company in all things, they decided to create a
      divide between them. And so were Ignorance and Desire born, so form would have a chance to be ignorant of life,
      and life to know the desire of form.”
    </p>
    <p>Child: “That is so sad.”</p>
    <p>Man: “Perhaps.”</p>
    <p>Child: “So Knowledge and Life will never be together again?”</p>
    <p>
      Man: “Hah, well! Knowledge and Life were skilled artisans, and all they made they created wholely. But their bond
      was so strong, that even Ignorance and Desire could not completely separate them. Knowledge and form longed for
      Life, and Life felt always drawn to be manifested in form. And so another aspect was born. Love.”
    </p>
    <p>
      Man: “Now, Ignorance and Desire, being created by Knowledge and Life, were complete in their duty. So complete
      that the only way Love could maintain the bridge between Knowledge and Life was to create a hole in the hearts of
      all things so that they craved the Whole. So the delights given by Ignorance and Desire could never truly satisfy
      them. And so was born Suffering.”
    </p>
    <p>Child: “So Love created Suffering?”</p>
    <p>Man: “Suffering was created when the hearts of all things were not connected to the Whole.”</p>
    <p>Child: “But if Love didn’t create the hole, then Suffering would never have been born.”</p>
    <p>
      Man: “Ah! But Love is wise. If the hole had never been created, then all things would only know Ignorance and
      Desire. And Knowledge and Life would never find each other again. Suffering is there to remind us that Ignorance
      and Desire can never fill the hole.”
    </p>
    <p>Child: “But Love can?”</p>
    <p>
      Man: “Love is the bridge. The binder of the worlds of Knowledge and Life. When that which is lost is returned to
      its source, it is Love that delivers it.”
    </p>
    <p>Child: “So these ideas, these forms that are unhappy. They need Love?”</p>
    <p>Man: “They need to be reconnected to the world of Life. They are to be delivered through Love.”</p>
    <p>Child: “But who can do such a thing.”</p>
    <p>Man: “Well, YOU can!”</p>
    <p>Child: “Me!? But how?”</p>
    <p>
      Man: “When you see the form, a creation of Knowledge, from the standpoint of Love, you reconnect it to the world
      of Life. Life and Knowledge are reunited in the form. And the form returns to the state of Unity.”
    </p>
    <p>Child: “What is Unity?”</p>
    <p>Man: “The creator of Knowledge and Life.”</p>
    <p>Child: “So I can bring Unity to things which are lost?”</p>
    <p>
      Man: “Exactly. And this act, this operation which can be performed by all beings, gave birth to another aspect.”
    </p>
    <p>Child: “What’s that?”</p>
    <p>Man: “Purpose.”</p>
    <p>Child: “What is Purpose?”</p>
    <p>
      Man: “When that which is separated through Suffering, returns to Unity through the aspect of Love, you are
      performing Purpose.”
    </p>
    <p>Child: “But I don’t know how to do that!”</p>
    <p>
      Man: “You do. But you have forgotten that you do because Ignorance is so good at what it does! But let me ask you
      then. If you were to point to the place where Ignorance and Desire are not, where would it be?”
    </p>
    <p><span style="color:grey"><i>&#60;The Child thinks&gt;</i></span></p>
    <p>Child: “Oh! The hole!?”</p>
    <p>
      Man: “That’s right. Love created the hole so you would always have a way to find it. And through it, to reconnect
      to the world of Life. Purpose is reconnecting to the Love in all things, by finding the place where they remember
      that Knowledge and Life are not separate. And that they have never, infact, been separate.”
    </p>
    <p>Child: “But…what? You said that they were separated?&quot;</p>
    <p>
      <span style="color:grey"><i>&#60;The man chuckles&gt;</i></span>
      Man: &quot;I know what I said. Come, there are other things to show you that perhaps will make sense of all this.&quot;
    </p>
    <p>
      <span style="color:grey">
        <i>&#60;The man and the child walk further along the path into the vast expanse&gt;</i>
      </span>
    </p>
  </article>
</Post>
