<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <p>I have not read many books on spiritual concepts.</p>
    <p>
      I mean I have read alchemical treatises, and various books related to techniques and theory. But I have never read
      books regarding states of consciousness.
    </p>
    <p>Why?</p>
    <p>
      Because I never found them useful. And yes I appreciate the irony of someone not finding use in reading about
      states of consciousness yet writing about them. Thank you!
    </p>
    <p><em>Seek that which you are not, and become all that you will ever be</em></p>
  </article>
</Post>
