<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="what-is-anamnesis"><a href="#what-is-anamnesis">🤔 What is anamnesis?</a></h2>
    <p>
      You remember how just before you incarnated there was that vending machine where you could select the style of
      eyelashes your meat-vehicle would grow to have? No? That&#39;s probably because you don&#39;t remember anything
      from before you were born.
    </p>
    <p>
      Now I&#39;m not here to discuss whether past-lives are real or not. All I&#39;m saying, is that in my experience
      there are things which have occured prior to our incarnating into a body.
    </p>
    <p>
      You see, I&#39;m a bit of an explorer of consciousness. And not the
      drop-a-few-tabs-of-acid-and-listen-to-Jane&#39;s-Addiction-while-I-journey- through-the-universe kind. While I
      have used substances and plants in the past, for the last 15 years my journey has been purely meditational. Or
      meditational based, I should say. The skill of silencing the mind can be applied to a variety of different
      practices, all of which lead to a greater understanding of this place we find ourselves in, and where we fit in
      it.
    </p>
    <p>
      I am certainly not the only one doing this. And I am definitely not the first. Countless others through the
      history of mankind have been driven to understand our reality via the use of meditation techniques. Whether it be
      for power, knowledge, understanding. Love. Devotion.
    </p>
    <p>Or to remember what it is that we have forgotten.</p>
    <p>And that is Anamnesis.</p>
    <p>
      <ImgZoom src="/about/plato_flash_mob.webp" alt="plato flash mob">
        A depiction of the first recorded flash mob
      </ImgZoom>
    </p>
    <p>
      <em>Anamnesis</em>
      is a word that comes from Plato, and is commonly translated as meaning
      <em>&quot;recollection&quot;</em>
      . Which is accurate-ish. But what Plato was referring to when using the word
      <em>anamnesis</em>
      , was the remembering of the innate knowledge that a person has acquired prior to this incarnation. Knowledge, or know-how,
      acquired from before this life.
    </p>
    <p>Okay. I lost you. I get it.</p>
    <p>
      But it has been my experience while delving into the realms within that we do have access to levels within us that
      contain memories, visions, and experiences, without having had them occur in this life. And the remembering, the
      re-owning, of these parts of myself have brought about realisations whose action on my consciousness have often
      been quite profound.
    </p>
    <p>This blog is simply about that.</p>
    <p>The rediscovering of our nature.</p>
    <p>
      And also other things. I love trying out stuff. Stuff is fun. And funnily enough, the years spent praticing the
      art of denying the senses to go within, has resulting in my greater appreciation for those senses. There are
      things to experience, both in and around us, and I love partaking in all the things on offer.
    </p>
  </article>
</Post>
